#!/bin/bash


function make_bootable() {
  pv_by_uuid="/dev/disk/by-uuid/$(ls -l /dev/disk/by-uuid/ | awk "/\/${pv##*/}\$/"' {print $9}')"
  if ! test "set" = "${pv_by_uuid:+set}"; then
    fail "Failed to find UUID for physical volume."
  fi
  sudo chroot "${target_mount_point}" /bin/bash -c 'DEBIAN_FRONTEND=noninteractive apt-get -y install linux-image-amd64' \
    || fail "Failed to install kernel package."
  sudo chroot "${target_mount_point}" /bin/bash -c 'DEBIAN_FRONTEND=noninteractive apt-get -y install grub-pc' \
    || fail "Failed to install grub-pc package."
  sudo chroot "${target_mount_point}" grub-install "${device}" \
    || fail "Failed to install grub (BIOS)."
  sudo chroot "${target_mount_point}" /bin/bash -c 'DEBIAN_FRONTEND=noninteractive apt-get -y remove grub-pc' \
    || fail "Failed to remove grub-pc package."
  sudo chroot "${target_mount_point}" /bin/bash -c 'DEBIAN_FRONTEND=noninteractive apt-get -y install grub-efi' \
    || fail "Failed to install grub-efi package."
  sudo chroot "${target_mount_point}" grub-install --removable --no-uefi-secure-boot --boot-directory /boot --efi-directory /boot/efi --recheck "${device}" \
    || fail "Failed to install grub (EFI)."
  sudo chroot "${target_mount_point}" update-grub \
    || fail "Failed to update grub configuration."
  template mkbs/crypttab /etc/crypttab
  #sudo cp "${target_mount_point}"/etc/lvm/lvm.conf{,.bak}
  #sudo sed -i "${target_mount_point}"/etc/lvm/lvm.conf '
  #  s/^multipath_component_detection.*$/multipath_component_detection = 0/;
  #  s/^md_component_detection.*$/md_component_detection = 0/;
  #  s/^udev_sync.*$/udev_sync = 0/;
  #  s/^udev_rules.*$/udev_rules = 0/;
  #'
  sudo chroot "${target_mount_point}" update-initramfs -u \
    || fail "Failed to update initramfs."
  #sudo mv "${target_mount_point}"/etc/lvm/lvm.conf{.bak,}
}
