#!/bin/bash


function partition() {
  sudo parted -s "${device}" mklabel gpt \
    || fail "Failed to write partition table."
  sudo parted -s "${device}" mkpart primary fat32 1MiB 2MiB \
    || fail "Failed to create BIOS boot partition."
  sudo parted -s "${device}" set 1 bios_grub on \
    || fail "Failed to set bios_grub flag."
  sudo parted -s "${device}" mkpart primary fat32 2MiB 256MiB \
    || fail "Failed to create ESP."
  sudo parted -s "${device}" set 2 esp on \
    || fail "Failed to set esp flag."
  # Apparent order of operations:
  #   parted writes partition
  #   parted returns
  #   old partition disappears
  #   new partition appears
  # Sleep to allow the old partition to disappear, THEN wait for the new partition to appear.
  sleep 1
  wait_for_device "${device}2"
  sudo mkfs.vfat "${device}2" \
    || fail "Failed to write FS to ESP."
  sudo parted -s "${device}" mkpart primary ext4 256MiB 512MiB \
    || fail "Failed to create boot partition."
  wait_for_device "${device}3"
  sudo mkfs.ext4 -F -L "${host}"_boot "${device}"3 \
    || fail "Failed to write FS to boot partition."
  sudo tune2fs -i 0 -c 0 "${device}"3 \
    || fail "Failed to tune FS parameters for boot partition."
  sudo parted -s "${device}" mkpart primary ext4 512MiB 100% \
    || fail "Failed to create root partition."
  wait_for_device "${device}4"
  # Are you sure you want to blow away this partition?  YES
  {
    echo -n $(
      pass show aaron/"${host}"/luks \
        || fail "Failed to retrieve password for LUKS."
    )
  } \
  | sudo cryptsetup luksFormat --key-file - "${device}"4 \
    || fail "Failed to format for LUKS."
  {
    echo -n $(
      pass show aaron/"${host}"/luks \
        || fail "Failed to retrieve password for LUKS."
    )
  } \
  | sudo cryptsetup open --key-file - --type luks "${device}"4 "${host}"_crypt \
    || fail "Failed to open LUKS volume."
  sudo pvcreate /dev/mapper/"${host}"_crypt \
    || fail "Failed to create LVM physical volume over LUKS."
  sudo vgcreate "${host}" /dev/mapper/"${host}"_crypt \
    || fail "Failed to create volume group over LUKS."
  sudo lvcreate -l 100%FREE -n root "${host}" \
    || fail "Failed to create logical volume for root."
  sudo mkfs.ext4 -F -L "${host}"_root /dev/mapper/"${host}"-root \
    || fail "Failed to write FS to root partition."
  sudo tune2fs -i 0 -c 0 /dev/mapper/"${host}"-root \
    || fail "Failed to tune FS parameters for root partition."
}
