#!/bin/bash


function write_fstab() {
  device_name="$(sed 's/.*\///g' <<< "${device}")"
  uuid=$(ls -l /dev/disk/by-uuid/ | grep "../../${device_name}2" | awk '{print $9}')
  grep -q . <<< "${uuid}" \
    || fail "Failed to determine ESP uuid."

  template mkbs/fstab /etc/fstab
}
