#!/bin/bash


function get_root() {
  output "We're going to need some root.  Authenticate for sudo."
  sudo -v || fail "Failed to get root."
}


function keep_root() {
  while sleep 60; do 
    sudo -v
  done
}


function drop_root() {
  keep_root_pid="${1:-unset}"
  if test 'unset' = "${keep_root_pid}"; then
    fail 'drop_root:  No PID specified.'
  fi
  kill $keep_root_pid || fail "Failed to kill sudo loop, PID:  ${keep_root_pid}"
}
