#!/bin/bash
#
# Not yet working.
#
# Stock image leaves trailing empty space.  This confuses my bad partitioning
# code.

hardware='jetson_nano'
#os='nvidia_debian'
#os='nvidia_ubuntu'
os='armbian'
active_interface_type='wireless'
