#!/bin/bash

hardware=raspberry_pi
os=raspios
unset use_big_partition
unset big_partition_mount_point
unset big_partition_label
active_interface_type=wireless
network_addressing=static
network_name=puppies
