#!/bin/bash

image_name='armbian.img'
disable_predictable_ifnames_for_armbian='y'

remove_files+=(
  '/etc/profile.d/armbian-check-first-login-reboot.sh'
  '/etc/profile.d/armbian-check-first-login.sh'
  '/root/.not_logged_in_yet'

)

null_link_files+=(
  '/etc/systemd/system/multi-user.target.wants/armbian-firstrun-config.service'
  '/lib/armbian/armbian-firstrun'
  '/lib/armbian/armbian-firstrun-config'
  '/lib/systemd/system/armbian-firstrun-config.service'
  '/lib/systemd/system/armbian-firstrun.service'
  '/lib/systemd/system/armbian-resize-filesystem.service'
  '/lib/systemd/system/sockets.target'
)
