#!/bin/bash

# On Armbian built for Jetson Nano, root is the second partition.  It is
# unclear whether this is a change in how Armbian works or a peculiarity of
# building for this board.
boot_partition_index=1
root_partition_index=2
big_partition_index=3

# More special casing for Armbian for Jetson Nano.  Apparently it comes with a
# messed up GPT label.
fix_gpt='yes'

image_name='armbian.img'
disable_predictable_ifnames_for_armbian='y'

remove_files+=(
  '/etc/profile.d/armbian-check-first-login-reboot.sh'
  '/etc/profile.d/armbian-check-first-login.sh'
  '/root/.not_logged_in_yet'
)

null_link_files+=(
  '/etc/systemd/system/multi-user.target.wants/armbian-firstrun-config.service'
  '/lib/armbian/armbian-firstrun'
  '/lib/armbian/armbian-firstrun-config'
  '/lib/systemd/system/armbian-firstrun-config.service'
  '/lib/systemd/system/armbian-firstrun.service'
  '/lib/systemd/system/armbian-resize-filesystem.service'
  '/lib/systemd/system/sockets.target'
)
