#!/bin/bash

image_name='nvidia_devuan.img'
root_partition_end='9GiB'
root_partition_index='1'
big_partition_index='13'
skip_resize_root='yes'
fix_gpt='yes'
big_partition_filesystem='ext4'
fstab_root_device='/dev/mmcblk0p1'
