#!/bin/bash

image_name=raspios.img
boot_partition_index=1
root_partition_index=2
big_partition_index=3
# Needed for first boot only.  Conditional logic should keep this from making
# trouble after that.
kick_wifi='yes'
