#!/bin/bash

image_name=raspios.img
boot_partition_index=1
root_partition_index=2
big_partition_index=3
# This makes networking work on first boot, at the cost of interrupting it
# briefly at every subsequent boot.
kick_wifi='yes'
