#!/bin/bash


function main() {
  get_root
  keep_root &
  keep_root_pid=$!
  get_pass "aaron/${host}/root"
  keep_pass "aaron/${host}/root" &
  keep_pass_pid=$!

  unmount_prep
  safety_net "${card_device}"

  #zero_out
  remove_partitions
  write_image

  if ! source vars/derived/partition; then
    echo "ERROR:  Failed to source:  vars/derived/partition" >&2
    exit 1
  fi

  resize_root_partition
  create_big_partition

  mount_root
  sync_big_partition 
  mount_nonroot

  configure_os

  unmount_nonroot
  unmount_root

  kill_loop "${keep_root_pid}"
  kill_loop "${keep_pass_pid}"
}
