#!/bin/bash


function write_image() {
  output "Writing image."
  # https://www.armbian.com/orange-pi-pc-plus/
  # https://dl.armbian.com/orangepipcplus/Debian_stretch_next.7z.torrent
  image="${image:-imageUnset}"
  card_device="${card_device:-deviceUnset}"
  test -e "${image}" \
    || fail "Image file not found:  '${image}'"
  test -b "${card_device}" \
    || fail "Device file not found:  '${card_device}'"
  eval dd if='"${image}"' bs=1M status=none \| pv "2>&${debug_level_command_output}" \| sudo dd bs=1M of='"${card_device}"' status=none ">&${debug_level_command_output}" \
    || fail "Failed to write image."
  if ! test 'set' = "${skip_resize_root:+set}"; then
    eval sudo parted -s '"${card_device}"' resizepart '"${root_partition_index}"' 10240MB ">&${debug_level_command_output}" \
      || fail "Failed to resize root partition."
    eval sudo e2fsck -fy '"${root_partition}"' ">&${debug_level_command_output}" \
      || fail "Failed to check root filesystem."
    eval sudo resize2fs '"${root_partition}"' ">&${debug_level_command_output}" \
      || fail "Failed to resize root filesystem."
  fi
  eval sudo tune2fs -i 0 -c 0 '"${root_partition}"' ">&${debug_level_command_output}" \
    || fail "Failed to tune root filesystem."
  if test 'set' = "${fix_gpt+set}"; then
    fix_gpt
  fi
}
