#!/bin/bash


read bs < "/sys/block/${card_device##*/}/queue/physical_block_size" || fail "Failed to get block size."

# This can't work until after writing the image.
#
# Assumption:  root is the last partition.
root_partition_end_original_bytes="$(
  sudo parted -s "${card_device}" unit B print \
    | tail -n 2 \
    | head -n 1 \
    | awk '{print $3}' \
    | sed 's/[^0-9]//g'
)"

root_partition_end_minimum_bytes="$(( root_partition_end_minimum_g * GiB - 1 ))"

echo "DEBUG:  root_partition_end_original_bytes='${root_partition_end_original_bytes}'"
echo "DEBUG:  root_partition_end_minimum_bytes='${root_partition_end_minimum_bytes}'"
echo "DEBUG:  root_partition_end_minimum_g='${root_partition_end_minimum_g}'"

if test "${root_partition_end_original_bytes}" -gt "${root_partition_end_minimum_bytes}"; then
  root_partition_end_bytes="${root_partition_end_original_bytes}"
else
  root_partition_end_bytes="${root_partition_end_minimum_bytes}"
fi

root_partition_end="${root_partition_end_bytes}B"

big_partition_start_bytes="$(( root_partition_end_bytes + 1 * bs ))"
big_partition_start="${big_partition_start_bytes}B"
big_partition_end_max_bytes="$(
  sudo parted -s "${card_device}" unit B print free \
    | tail -n 2 \
    | head -n 1 \
    | awk '{print $2}' \
    | sed 's/B$//'
)"
# The redundant looking (integer) math is important.
big_partition_end="$(( ( big_partition_end_max_bytes / bs ) * bs - 1 ))B"
