#!/bin/bash

function rescan_storage() {
  for scan_file in /sys/class/scsi_host/host*/scan; do
    output "Initiating storage scan:  ${scan_file}"
    echo '- - -' \
    | sudo tee $scan_file >/dev/null \
    || fail "Failed to initate storage scan:  ${scan_file}"
  done
}


function wait_for_device() {
  local device="${1}"

  # Give it a moment to disappear before waiting for it to come back.
  sleep 2

  output "Waiting for device:  ${device}"
  for i in {0..99}; do
    if test -b "${device}"; then
      echo
      output "Device has appeared:  ${device}"
      return 0
    fi
    echo -n .
    sleep .1
  done
  fail "Device did not appear:  ${device}"
}
