#!/bin/bash


function template() {
  test 2 = "${#}" \
    || fail "template:  Wrong number of arguments; expected 2, recieved:  ${#}"

  conf_name="${1}"
  target_path="${2}"

  # eval here allows use of variables inside the template file.
  eval content="\"$(cat templates/${conf_name})\""

  output "Templating:  ${target_mount_point}${target_path}"
  sudo tee "${target_mount_point}${target_path}" \
    <<< "${content}" \
    || fail "Failed to write:  ${target_path}" 
}
