#!/bin/bash


function template() {
  test 2 = "${#}" \
    || fail "template:  Wrong number of arguments; expected 2, recieved:  ${#}"

  conf_name="${1}"
  target_path="${2}"

  #eval "${conf_name}"="\"$(cat templates/${conf_name})\""
  content="$(cat templates/${conf_name})"

  sudo tee "${target_mount_point}""${target_path}" \
    <<< "${content}" \
    || fail "Failed to write:  ${target_path}" 
}
