#!/bin/bash


function write_root_password_hash() {
  if sudo grep -q ^root "${target_mount_point}"/etc/shadow; then
    output "Generating shadow line."
    shadow_line="$(shadow_line root)" \
      || fail "Failed to generate shadow line."
    # Shadow line can contain slashes.
    output "Fixing line for root in /etc/shadow."
    sudo sed -i 's#^root:.*$#'"${shadow_line}"'#' "${target_mount_point}"/etc/shadow \
      || fail "Failed to write password hash for root."
  else
    output "Writing line for root to /etc/shadow."
    shadow_line root | sudo tee -a "${target_mount_point}"/etc/shadow \
      || fail "Failed to write shadow line for root."
  fi
}
