#!/bin/bash


function main() {
  get_root
  keep_root &
  keep_root_pid=$!
  get_pass
  keep_pass &
  keep_pass_pid=$!

  unmount_prep
  safety_net "${card_device}"

  write_image
  create_big_partition

  mount_root
  sync_big_partition 
  mount_nonroot

  configure_os

  unmount_nonroot
  unmount_root

  kill_loop "${keep_root_pid}"
  kill_loop "${keep_pass_pid}"
}
