#!/bin/bash

remove_files=(
  '/etc/ssh/ssh_host_*_key*'
)

null_link_files=(
  '/etc/init.d/dhcpcd'
  '/etc/systemd/network/99-default.link'
  '/etc/systemd/system/default.target.wants/avahi-daemon.service'
  '/etc/systemd/system/default.target.wants/dhcpcd.service'
  '/etc/systemd/system/default.target.wants/nfs-client.target'
  '/etc/systemd/system/default.target.wants/remote-fs.target'
  '/etc/systemd/system/default.target.wants/triggerhappy.service'
  '/etc/systemd/system/multi-user.target.wants/NetworkManager.service'
  '/lib/systemd/system/NetworkManager.service'
  '/lib/systemd/system/dhcpcd.service'
  '/var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/NetworkManager.service'
)
