#!/bin/bash

wired_interface='eth0'
wireless_interface='wlan0'
active_interface_type='wired'
network_name='puppies'
network_addressing='static'
netmask='255.255.255.0'
netmask_bits='24'
gateway='192.168.11.1'
dns_server='192.168.11.54'
