#!/bin/bash

unset boot_partition_index

root_partition_index='1'
root_partition_end_minimum_g='10'

use_big_partition='1'
big_partition_index='2'
big_partition_label='log'
big_partition_mount_point='/var/log'
big_partition_filesystem='f2fs'
